module.exports = {
	CLIENT_ID: 'KAFKA_NODE',

	API_VERSION: 2,

	PRODUCE: 0,
	FETCH: 1,
	OFFSETS: 2,
	METADATA: 3,
	LEADER_AND_ISR: 4,
	OFFSETS_FETCH: 9,
	FIND_COORDINATOR: 10,
	JOIN_GROUP: 11,
	HEARTBEAT: 12,
	DESCRIBE_GROUPS: 15,
};